# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1299863021);
user_pref("app.update.lastUpdateTime.background-update-timer", 1299862857);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1299862613);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1299862560);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1299861974);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1299861863);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.15");
user_pref("extensions.enabledItems", "{e968fc70-8f95-4ab9-9e79-304de2a71ee1}:0.7.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.15");
user_pref("extensions.lastAppVersion", "3.6.15");
user_pref("extensions.update.notifyUser", false);
user_pref("general.useragent.extra.firefox", "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0_1 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A306 Safari/6531.22.7");
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1302453843);
user_pref("useragentswitcher.import.overwrite", false);
user_pref("useragentswitcher.menu.hide", false);
user_pref("useragentswitcher.version", "0.73");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
